id: P004493
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21845
  title: གློག་ཀླད་ལ་འཇུག་པའི་རྨང་གཞིའི་ཤེས་བྱ།
  author: ''
  volumes:
    ce5a875dc3ce44b19b8ad8c8c41450e3:
      image_group_id: I1KG22031
      title: ''
      volume_number: 1
      total_pages: 370
