id: I4F4F4BDA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:29:26+00:00'
last_modified: '2022-06-08T01:28:29.137705+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21845
  title: གློག་ཀླད་ལ་འཇུག་པའི་རྨང་གཞིའི་ཤེས་བྱ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C118:
      image_group_id: I1KG22031
      title: ''
      total_pages: 370
      order: 1
      base_file: C118.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
